version: "3.9"

services:
    signature-mash:
        image: signature-mash
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./src:/app/src
            - ./tsconfig.json:/app/tsconfig.json
            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
