version: "3.9"

services:
    signature-mash:
        image: signature-mash
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
